from __future__ import annotations

import os
from pathlib import Path

import pytest

from bookflow import BookflowError
from bookflow.documentation import generate as generation
from bookflow.documentation.examples import EXAMPLES


def test_render_tree_is_deterministic_complete_and_model_valid(monkeypatch, tmp_path):
    from bookflow.core import registry
    from bookflow.company import schema as company_schema
    from bookflow.hub import schema as hub_schema

    first = generation.render_tree()
    second = generation.render_tree()
    monkeypatch.chdir(tmp_path)
    from_another_working_directory = generation.render_tree()
    assert first == second
    assert first == from_another_working_directory
    commands = registry.all_commands(include_standalone=True)
    assert set(EXAMPLES) == {command.name for command in commands}
    assert {path for path in first if path.startswith("cli/")} == {
        f"cli/{command.noun.replace(' ', '-')}.md" for command in commands
    }
    expected_schema = {
        f"schema/{scope}/{table.name}.md"
        for scope, metadata in (("hub", hub_schema.metadata), ("company", company_schema.metadata))
        for table in metadata.sorted_tables
    }
    assert {path for path in first if path.startswith("schema/")} == expected_schema
    assert {generation.MARKER, "index.md", "concepts.md", "agent-guide.md"} <= set(first)
    assert all(b"/home/" not in body and b"Generated by" in body for path, body in first.items() if path.endswith(".md") and path not in generation.RESOURCE_NAMES)
    for command in commands:
        page = first[f"cli/{command.noun.replace(' ', '-')}.md"].decode()
        start = page.index(f"## `{command.name}`")
        end = page.find("\n## `", start + 4)
        section = page[start:] if end == -1 else page[start:end]
        assert f"| Required role | {command.authorization_requirement} |" in section
        capability = "none" if not command.permissioned else command.capability
        assert f"| Capability | {capability or '—'} |" in section
        assert f"| Feature | {command.feature or '—'} |" in section
        assert f"| HTTP | {generation._http_route(command)} |" in section
        for code in command.error_codes:
            assert f"| `{code}` |" in section
        for name, _requirement, _description in generation._http_headers(command):
            assert f"| {name} |" in section
        for field in generation.model_fields(command.input_model, leaves_only=True):
            assert f"`{field.path}`" in section
        for field in generation.model_fields(command.output_model):
            assert f"`{field.path}`" in section

    serve_page = first["cli/serve.md"].decode()
    assert "readiness line is written to stderr" in serve_page
    assert "handed to the running host through its local socket" in serve_page
    index = first["index.md"].decode()
    assert "Start with the agent guide" in index
    assert "complete authenticated HTTP write" in index
    audit_page = first["cli/audit.md"].decode()
    assert "Lower-bound cursor used for this request" in audit_page
    assert "Touched-record details returned by audit show" in audit_page


def test_generate_check_and_stale_diagnostics_are_exact_and_read_only(tmp_path):
    output = tmp_path / "docs"
    paths = generation.generate_docs(str(output), False)
    assert paths == sorted(generation.render_tree())
    before = {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()}
    assert generation.generate_docs(str(output), True) == paths

    (output / "index.md").write_text("changed\n")
    (output / "agent-guide.md").unlink()
    (output / "extra.md").write_text("extra\n")
    stale_state = {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()}
    with pytest.raises(BookflowError) as caught:
        generation.generate_docs(str(output), True)
    assert caught.value.code == "E_DOCS_STALE"
    assert caught.value.details == {
        "missing": ["agent-guide.md"],
        "extra": ["extra.md"],
        "changed": ["index.md"],
    }
    assert {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()} == stale_state
    assert before != stale_state


def test_generation_refuses_unowned_and_symlinked_destinations(tmp_path):
    unrelated = tmp_path / "unrelated"
    unrelated.mkdir()
    (unrelated / "mine.txt").write_text("keep")
    with pytest.raises(BookflowError) as caught:
        generation.generate_docs(str(unrelated), False)
    assert caught.value.code == "E_USAGE" and (unrelated / "mine.txt").read_text() == "keep"

    real = tmp_path / "real"
    real.mkdir()
    link = tmp_path / "link"
    link.symlink_to(real, target_is_directory=True)
    for check in (False, True):
        with pytest.raises(BookflowError) as caught:
            generation.generate_docs(str(link), check)
        assert caught.value.code == "E_USAGE"


def test_failed_stage_preserves_the_previous_complete_tree(tmp_path, monkeypatch):
    output = tmp_path / "docs"
    generation.generate_docs(str(output), False)
    before = {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()}
    real_write_stage = generation._write_stage

    def fail_stage(stage: Path, tree: dict[str, bytes]) -> None:
        first = next(iter(tree.items()))
        real_write_stage(stage, {first[0]: first[1]})
        raise OSError("simulated stage failure")

    monkeypatch.setattr(generation, "_write_stage", fail_stage)
    with pytest.raises(OSError, match="simulated"):
        generation.generate_docs(str(output), False)
    after = {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()}
    assert after == before
    assert not list(tmp_path.glob(".docs.stage-*")) and not list(tmp_path.glob(".docs.backup-*"))


def test_failed_swap_restores_the_previous_complete_tree(tmp_path, monkeypatch):
    output = tmp_path / "docs"
    generation.generate_docs(str(output), False)
    before = {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()}
    real_replace = generation._replace
    calls = 0

    def fail_second(source: Path, destination: Path) -> None:
        nonlocal calls
        calls += 1
        if calls == 2:
            raise OSError("simulated swap failure")
        real_replace(source, destination)

    monkeypatch.setattr(generation, "_replace", fail_second)
    with pytest.raises(OSError, match="simulated"):
        generation.generate_docs(str(output), False)
    after = {path.relative_to(output).as_posix(): path.read_bytes() for path in output.rglob("*") if path.is_file()}
    assert after == before
    assert not list(tmp_path.glob(".docs.stage-*")) and not list(tmp_path.glob(".docs.backup-*"))


def test_emitted_links_resolve(tmp_path):
    output = tmp_path / "docs"
    generation.generate_docs(str(output), False)
    import re

    for page in output.rglob("*.md"):
        for target in re.findall(r"\[[^]]+\]\(([^)]+)\)", page.read_text()):
            if "://" not in target and not target.startswith("#"):
                assert (page.parent / target.split("#", 1)[0]).resolve().is_file(), (page, target)


def test_versioned_work_and_allocation_branches_remain_documented():
    from bookflow.company.work_outputs import WorkWriteOutput
    from bookflow.company.sales_outputs import SalesWriteOutput
    fields={field.path:field for field in generation.model_fields(WorkWriteOutput)}
    assert 'revision.facts.profile.sales_tax_calculation' in fields
    assert 'revision.lines[].facts.estimated_unit_cost_minor_units' in fields
    assert fields['revision.facts.schema_version'].type=='literal[1] | literal[2]'
    sales={field.path for field in generation.model_fields(SalesWriteOutput)}
    assert 'revision.lines[].item_snapshot.allocation_proof.basis_version' in sales
    assert 'revision.billing_sources[].allocation_proof.basis_version' in sales
