"""Render and atomically publish the complete Bookflow documentation tree."""

from __future__ import annotations

import json
import os
import shutil
import tempfile
from importlib import resources
from pathlib import Path
from typing import Any

from bookflow.core.errors import ALL_CODES, INFRASTRUCTURE_CODES, BookflowError
from bookflow.documentation.examples import EXAMPLES
from bookflow.documentation.introspection import model_fields, sample_model, table_columns

MARKER = ".bookflow-generated"
MARKER_BYTES = b"bookflow documentation tree\n"
NOTICE = "<!-- Generated by `bookflow docs generate`; do not edit this file directly. -->\n\n"
RESOURCE_NAMES = ("concepts.md", "agent-guide.md")
STANDALONE_INFRASTRUCTURE_CODES = ("E_USAGE", "E_VALIDATION", "E_CONTEXT_IN_INPUT", "E_IO", "E_INTERNAL")


def _text(value: Any) -> str:
    if value is None or value == "":
        return "—"
    return str(value).replace("|", "\\|").replace("\n", "<br>")


def _command_options(cmd: Any) -> list[tuple[str, str]]:
    json_meaning = (
        "Print one JSON object on stdout after orderly shutdown; the readiness line is written to stderr."
        if cmd.name == "serve"
        else "Print one JSON object."
    )
    options = [("`--json`", json_meaning)]
    if not getattr(cmd, "standalone", False):
        options.append(("`--data-root TEXT`", "Data root; otherwise `BOOKFLOW_DATA_ROOT`, then `~/.bookflow`."))
    if cmd.is_write:
        options.extend([
            ("`--dry-run`", "Validate and preview without writing."),
            ("`--reason TEXT`", "Short reason for the write."),
            ("`--source-ref TEXT`", "Identifier of the source that triggered the write."),
            ("`--interactive`", "Prompt for input fields not supplied as arguments or options."),
        ])
        if cmd.scope == "company":
            options.append(("`--directive TEXT`", "Standing-instruction code or id cited by the write."))
    if cmd.accepts_idempotency_key:
        options.append(("`--idempotency-key TEXT`", "Retry-safe key for this create command."))
    if cmd.clearable:
        options.append(("`--clear FIELD`", "Set a nullable field to null; repeatable."))
    if cmd.streams:
        options.append(("`--follow`", "Keep polling and emit each new event until interrupted."))
    if cmd.scope == "company":
        options.append(("`--company TEXT`", "Company id, `Organization/Company`, or display name."))
    return options


def _field_flag(cmd: Any, path: str, secret: bool) -> str:
    if path in cmd.positional:
        return f"`{path.upper()}`"
    flag = path.replace(".", "-").replace("_", "-")
    suffix = " (secret)" if secret else ""
    return f"`--{flag}`{suffix}"


def _http_route(cmd: Any) -> str:
    if cmd.local_only:
        return "Local only; no HTTP route."
    dotted = cmd.name.replace(" ", ".")
    if cmd.scope == "company":
        return f"`POST /companies/{{company_id}}/commands/{dotted}`"
    return f"`POST /commands/{dotted}`"


def _http_headers(cmd: Any) -> list[tuple[str, str, str]]:
    if cmd.local_only:
        return []
    headers = [
        ("`Authorization`", "required for bearer clients", "`Bearer <secret>`"),
        ("`X-Bookflow-Client-Name`", "optional", "Stable caller name recorded in audit"),
        ("`X-Bookflow-Client-Version`", "optional", "Caller version recorded in audit"),
    ]
    if cmd.scope == "company":
        headers.append(("`X-Bookflow-Company`", "optional", "If sent, must equal the company ULID in the route"))
    if cmd.is_write:
        headers.extend([
            ("`X-Bookflow-Reason`", "conditional", "Short reason; an agent or system write needs this or an active directive"),
            ("`X-Bookflow-Source-Ref`", "optional", "Identifier of the source that triggered the write"),
        ])
        if cmd.scope == "company":
            headers.append(("`X-Bookflow-Directive`", "conditional", "Active directive code or id; alternative to reason for an agent or system write"))
    if cmd.accepts_idempotency_key:
        headers.append(("`Idempotency-Key`", "optional", "Retry-safe key for this create command"))
    return headers


def _command_page(noun: str, commands: list[Any]) -> bytes:
    lines = [NOTICE.rstrip(), "", f"# `{noun}` commands", ""]
    for cmd in commands:
        capability = "none" if not getattr(cmd, "permissioned", True) else cmd.capability
        lines.extend([
            f"## `{cmd.name}`",
            "",
            cmd.description,
            "",
            "| Contract | Value |",
            "|---|---|",
            f"| Scope | {_text(cmd.scope)} |",
            f"| Kind | {_text(cmd.kind)} |",
            f"| Required role | {_text(cmd.authorization_requirement)} |",
            f"| Capability | {_text(capability)} |",
            f"| Feature | {_text(cmd.feature)} |",
            f"| HTTP | {_text(_http_route(cmd))} |",
            "",
            "### CLI",
            "",
            f"`{EXAMPLES[cmd.name].invocation}`",
            "",
            "### Input",
            "",
            "| JSON field | CLI input | Type | Required | Nullable | Default | Description and constraints |",
            "|---|---|---|---|---|---|---|",
        ])
        fields = model_fields(cmd.input_model, leaves_only=True)
        if fields:
            for field in fields:
                details = "; ".join(item for item in (field.description, field.constraints) if item) or "—"
                lines.append(
                    f"| `{field.path}` | {_field_flag(cmd, field.path, field.secret)} | {_text(field.type)} | "
                    f"{'yes' if field.required else 'no'} | {'yes' if field.nullable else 'no'} | {_text(field.default)} | {_text(details)} |"
                )
        else:
            lines.append("| — | — | — | — | — | — | This command has no input fields. |")
        lines.extend([
            "",
            "### Command and context options",
            "",
            "| Option | Meaning |",
            "|---|---|",
        ])
        lines.extend(f"| {name} | {_text(description)} |" for name, description in _command_options(cmd))
        lines.extend(["", "### HTTP", ""])
        headers = _http_headers(cmd)
        if not headers:
            lines.append("This command has no HTTP route.")
        else:
            lines.extend([
                f"Route: {_http_route(cmd)}",
                "",
                "Send the input object as JSON. Authentication may instead come from a browser session cookie.",
                "",
                "| Header | Requirement | Meaning |",
                "|---|---|---|",
            ])
            lines.extend(f"| {name} | {requirement} | {_text(description)} |" for name, requirement, description in headers)
        lines.extend([
            "",
            "### Output",
            "",
            "| JSON field | Type | Required | Nullable | Default | Description |",
            "|---|---|---|---|---|---|",
        ])
        for field in model_fields(cmd.output_model):
            lines.append(
                f"| `{field.path}` | {_text(field.type)} | {'yes' if field.required else 'no'} | "
                f"{'yes' if field.nullable else 'no'} | {_text(field.default)} | {_text(field.description)} |"
            )
        lines.extend(["", "Example JSON output:", "", "```json"])
        lines.extend(json.dumps(sample_model(cmd.output_model), indent=2, sort_keys=True).splitlines())
        lines.extend(["```", "", "### Errors", "", "| Code | Meaning |", "|---|---|"])
        common = list(STANDALONE_INFRASTRUCTURE_CODES) if getattr(cmd, "standalone", False) else list(INFRASTRUCTURE_CODES)
        codes = list(dict.fromkeys([*cmd.error_codes, *common]))
        for code in sorted(codes):
            lines.append(f"| `{code}` | {_text(ALL_CODES[code])} |")
        if cmd.name == "serve":
            lines.extend([
                "",
                "`serve` is long-running. Its readiness line is written to stderr and its JSON output to stdout during orderly shutdown. It holds the data-root lock until interrupted, but compatible CLI and Python calls on the same machine are handed to the running host through its local socket; they do not compete for the lock. A second host or an incompatible local client can receive `E_DB_BUSY`.",
            ])
        lines.append("")
    return ("\n".join(lines).rstrip() + "\n").encode()


def _schema_page(database: str, table: Any) -> bytes:
    description = str(table.info.get("description", "")).strip()
    if not description:
        raise ValueError(f"{database}.{table.name}: missing table description")
    columns = table_columns(table)
    missing = [column.name for column in columns if not column.description]
    if missing:
        raise ValueError(f"{database}.{table.name}: missing column descriptions: {', '.join(missing)}")
    lines = [
        NOTICE.rstrip(),
        "",
        f"# `{database}.{table.name}`",
        "",
        description,
        "",
        f"Database: `{database}`.",
        "",
        "| Column | SQL type | Nullable | Default | Key | Indexes | References | Meaning |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for column in columns:
        lines.append(
            f"| `{column.name}` | {_text(column.type)} | {'yes' if column.nullable else 'no'} | {_text(column.default)} | "
            f"{_text(column.key)} | {_text(column.indexes)} | {_text(column.references)} | {_text(column.description)} |"
        )
    return ("\n".join(lines) + "\n").encode()


def _resource(name: str) -> bytes:
    body = resources.files("bookflow.documentation").joinpath("resources").joinpath(name).read_bytes()
    return body.replace(b"\r\n", b"\n")


def render_tree() -> dict[str, bytes]:
    from bookflow.core import registry
    from bookflow.company import schema as company_schema
    from bookflow.hub import schema as hub_schema

    registry.load_all()
    commands = registry.all_commands(include_standalone=True)
    missing_examples = sorted(set(command.name for command in commands) - set(EXAMPLES))
    extra_examples = sorted(set(EXAMPLES) - set(command.name for command in commands))
    if missing_examples or extra_examples:
        raise ValueError(f"command example mismatch: missing={missing_examples}, extra={extra_examples}")
    for command in commands:
        command.input_model.model_validate(EXAMPLES[command.name].input)
        sample_model(command.output_model)

    tree: dict[str, bytes] = {MARKER: MARKER_BYTES}
    for name in RESOURCE_NAMES:
        tree[name] = _resource(name)

    nouns: dict[str, list[Any]] = {}
    for command in commands:
        nouns.setdefault(command.noun, []).append(command)
    for noun in sorted(nouns):
        slug = noun.replace(" ", "-")
        tree[f"cli/{slug}.md"] = _command_page(noun, sorted(nouns[noun], key=lambda item: item.name))

    for database, metadata in (("hub", hub_schema.metadata), ("company", company_schema.metadata)):
        for table in metadata.sorted_tables:
            tree[f"schema/{database}/{table.name}.md"] = _schema_page(database, table)

    lines = [
        NOTICE.rstrip(),
        "",
        "# Bookflow documentation",
        "",
        "Start with the agent guide for a complete authenticated HTTP write. Read concepts for the shared behavior behind every command surface, then use the generated references for exact inputs and outputs.",
        "",
        "- [Agent guide](agent-guide.md) — install or select the command, start an isolated host, and complete a versioned audited write.",
        "- [Concepts](concepts.md) — selection, context, concurrency, audit, identity, money, and error behavior.",
        "",
        "## Command reference",
        "",
    ]
    lines.extend(f"- [`{noun}`](cli/{noun.replace(' ', '-')}.md)" for noun in sorted(nouns))
    lines.extend(["", "## Schema reference", ""])
    for path in sorted(path for path in tree if path.startswith("schema/")):
        label = path.removeprefix("schema/").removesuffix(".md")
        lines.append(f"- [`{label}`]({path})")
    tree["index.md"] = ("\n".join(lines).rstrip() + "\n").encode()
    return dict(sorted(tree.items()))


def _state(path: Path) -> dict[str, bytes]:
    if not path.exists():
        return {}
    if path.is_symlink() or not path.is_dir():
        raise BookflowError("E_USAGE", message="The documentation output must be a real directory, not a file or symlink.")
    state: dict[str, bytes] = {}
    for item in sorted(path.rglob("*")):
        if item.is_symlink():
            raise BookflowError("E_USAGE", message="The documentation output may not contain symlinks.")
        if item.is_file():
            state[item.relative_to(path).as_posix()] = item.read_bytes()
    return state


def _differences(expected: dict[str, bytes], actual: dict[str, bytes]) -> dict[str, list[str]]:
    expected_paths, actual_paths = set(expected), set(actual)
    return {
        "missing": sorted(expected_paths - actual_paths),
        "extra": sorted(actual_paths - expected_paths),
        "changed": sorted(path for path in expected_paths & actual_paths if expected[path] != actual[path]),
    }


def _replace(source: Path, destination: Path) -> None:
    os.replace(source, destination)


def _write_stage(stage: Path, tree: dict[str, bytes]) -> None:
    for relative, body in tree.items():
        target = stage / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(body)


def generate_docs(output: str, check: bool) -> list[str]:
    requested = Path(output).expanduser()
    if requested.is_symlink():
        raise BookflowError("E_USAGE", message="The documentation output may not be a symlink.")
    target = requested.resolve()
    tree = render_tree()
    if check:
        differences = _differences(tree, _state(target))
        if any(differences.values()):
            raise BookflowError("E_DOCS_STALE", details=differences)
        return sorted(tree)

    if target.exists():
        current = _state(target)
        if current and current.get(MARKER) != MARKER_BYTES:
            raise BookflowError("E_USAGE", message="The non-empty documentation output is not owned by Bookflow.")
    target.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix=f".{target.name}.stage-", dir=target.parent))
    backup: Path | None = None
    try:
        _write_stage(stage, tree)
        if _differences(tree, _state(stage)) != {"missing": [], "extra": [], "changed": []}:
            raise OSError("staged documentation failed validation")
        if target.exists():
            backup = Path(tempfile.mkdtemp(prefix=f".{target.name}.backup-", dir=target.parent))
            backup.rmdir()
            _replace(target, backup)
        _replace(stage, target)
    except Exception:
        if backup is not None and backup.exists() and not target.exists():
            _replace(backup, target)
        if stage.exists():
            shutil.rmtree(stage)
        raise
    if backup is not None and backup.exists():
        shutil.rmtree(backup)
    return sorted(tree)
