"""Immutable domestic journal revisions and posting effects.

Revision ID: co0007
Revises: co0006
"""

from alembic import op

revision = "co0007"
down_revision = "co0006"

DDL = (
    "CREATE TABLE transactions (\n\tid VARCHAR(26) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\tupdated_at VARCHAR(32) NOT NULL, \n\tupdated_by VARCHAR(26) NOT NULL, \n\tupdated_via VARCHAR(16) NOT NULL, \n\ttype VARCHAR(32) NOT NULL, \n\tnumber VARCHAR(64) NOT NULL, \n\tcurrent_revision_id VARCHAR(26) NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tvoided_at VARCHAR(32), \n\tvoided_by VARCHAR(26), \n\tvoid_reason VARCHAR(140), \n\tvoid_posting_batch_id VARCHAR(26), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_transaction_type_number UNIQUE (type, number), \n\tCONSTRAINT ck_transaction_type CHECK (type = 'journal_entry'), \n\tCONSTRAINT ck_transaction_number CHECK (length(trim(number)) BETWEEN 1 AND 64), \n\tCONSTRAINT ck_transaction_void CHECK ((status = 'posted' AND voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL AND void_posting_batch_id IS NULL) OR (status = 'voided' AND voided_at IS NOT NULL AND voided_by IS NOT NULL AND length(trim(void_reason)) > 0 AND void_posting_batch_id IS NOT NULL)), \n\tCONSTRAINT fk_transaction_current_revision FOREIGN KEY(id, current_revision_id) REFERENCES transaction_revisions (transaction_id, id) DEFERRABLE INITIALLY DEFERRED, \n\tCONSTRAINT fk_transaction_void_batch FOREIGN KEY(id, void_posting_batch_id) REFERENCES posting_batches (transaction_id, id) DEFERRABLE INITIALLY DEFERRED\n)",
    "CREATE TABLE transaction_revisions (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\trevision_number BIGINT NOT NULL, \n\tsupersedes_revision_id VARCHAR(26), \n\tdate VARCHAR(10) NOT NULL, \n\tnumber VARCHAR(64) NOT NULL, \n\tname_type VARCHAR(16), \n\tname_id VARCHAR(26), \n\tmemo VARCHAR(2000), \n\ttotal_minor_units BIGINT NOT NULL, \n\tcurrency VARCHAR(3) NOT NULL, \n\tissuer_snapshot TEXT NOT NULL, \n\tcustom_fields_snapshot TEXT NOT NULL, \n\taudit_event_id VARCHAR(26) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_revision_document_id UNIQUE (transaction_id, id), \n\tCONSTRAINT uq_revision_number UNIQUE (transaction_id, revision_number), \n\tCONSTRAINT uq_revision_successor UNIQUE (supersedes_revision_id), \n\tCONSTRAINT fk_revision_supersedes FOREIGN KEY(transaction_id, supersedes_revision_id) REFERENCES transaction_revisions (transaction_id, id), \n\tCONSTRAINT ck_ledger_revision_number_positive CHECK (typeof(revision_number) = 'integer' AND revision_number > 0), \n\tCONSTRAINT ck_ledger_total_minor_units_positive CHECK (typeof(total_minor_units) = 'integer' AND total_minor_units > 0), \n\tCONSTRAINT ck_ledger_issuer_snapshot_object CHECK (json_valid(issuer_snapshot) AND json_type(issuer_snapshot) = 'object'), \n\tCONSTRAINT ck_ledger_custom_fields_snapshot_object CHECK (json_valid(custom_fields_snapshot) AND json_type(custom_fields_snapshot) = 'object'), \n\tFOREIGN KEY(transaction_id) REFERENCES transactions (id), \n\tFOREIGN KEY(audit_event_id) REFERENCES audit_events (id)\n)",
    'CREATE TABLE document_line_identities (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_line_identity_document UNIQUE (transaction_id, id), \n\tFOREIGN KEY(transaction_id) REFERENCES transactions (id)\n)',
    "CREATE TABLE document_lines (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tline_id VARCHAR(26) NOT NULL, \n\tposition BIGINT NOT NULL, \n\tkind VARCHAR(16) NOT NULL, \n\taccount_id VARCHAR(26) NOT NULL, \n\tside VARCHAR(6) NOT NULL, \n\tamount_minor_units BIGINT NOT NULL, \n\tcurrency VARCHAR(3) NOT NULL, \n\taccount_snapshot TEXT NOT NULL, \n\tname_type VARCHAR(16), \n\tname_id VARCHAR(26), \n\tparty_name VARCHAR(200), \n\tclass_id VARCHAR(26), \n\tclass_name VARCHAR(200), \n\tdescription VARCHAR(2000), \n\toriginal_minor_units BIGINT, \n\toriginal_currency VARCHAR(3), \n\trate_used VARCHAR(128), \n\trate_source VARCHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_document_line_revision FOREIGN KEY(transaction_id, revision_id) REFERENCES transaction_revisions (transaction_id, id), \n\tCONSTRAINT fk_document_line_identity FOREIGN KEY(transaction_id, line_id) REFERENCES document_line_identities (transaction_id, id), \n\tCONSTRAINT uq_document_line_owner UNIQUE (transaction_id, revision_id, id), \n\tCONSTRAINT uq_document_line_identity UNIQUE (revision_id, line_id), \n\tCONSTRAINT uq_document_line_position UNIQUE (revision_id, position), \n\tCONSTRAINT ck_ledger_position_positive CHECK (typeof(position) = 'integer' AND position > 0), \n\tCONSTRAINT ck_ledger_amount_minor_units_positive CHECK (typeof(amount_minor_units) = 'integer' AND amount_minor_units > 0), \n\tCONSTRAINT ck_ledger_account_snapshot_object CHECK (json_valid(account_snapshot) AND json_type(account_snapshot) = 'object'), \n\tCONSTRAINT ck_ledger_party_pair CHECK ((name_type IS NULL AND name_id IS NULL) OR (name_type IN ('customer','vendor','employee','other_name') AND name_id IS NOT NULL)), \n\tCONSTRAINT ck_ledger_foreign_facts CHECK ((original_minor_units IS NULL AND original_currency IS NULL AND rate_used IS NULL AND rate_source IS NULL) OR (typeof(original_minor_units) = 'integer' AND original_minor_units > 0 AND original_currency IS NOT NULL AND rate_used IS NOT NULL AND rate_source IS NOT NULL)), \n\tCONSTRAINT ck_document_line_kind_side CHECK (kind = 'journal' AND side IN ('debit', 'credit')), \n\tFOREIGN KEY(account_id) REFERENCES accounts (id), \n\tFOREIGN KEY(class_id) REFERENCES classes (id)\n)",
    "CREATE TABLE posting_batches (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tkind VARCHAR(16) NOT NULL, \n\teffective_date VARCHAR(10) NOT NULL, \n\treverses_batch_id VARCHAR(26), \n\treplaces_batch_id VARCHAR(26), \n\taudit_event_id VARCHAR(26) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_batch_document UNIQUE (transaction_id, id), \n\tCONSTRAINT uq_batch_reversal UNIQUE (reverses_batch_id), \n\tCONSTRAINT uq_batch_replacement UNIQUE (replaces_batch_id), \n\tCONSTRAINT fk_batch_revision FOREIGN KEY(transaction_id, revision_id) REFERENCES transaction_revisions (transaction_id, id), \n\tCONSTRAINT fk_batch_reverses FOREIGN KEY(transaction_id, reverses_batch_id) REFERENCES posting_batches (transaction_id, id), \n\tCONSTRAINT fk_batch_replaces FOREIGN KEY(transaction_id, replaces_batch_id) REFERENCES posting_batches (transaction_id, id), \n\tCONSTRAINT ck_batch_kind_links CHECK ((kind = 'original' AND reverses_batch_id IS NULL AND replaces_batch_id IS NULL) OR (kind = 'reversal' AND reverses_batch_id IS NOT NULL AND replaces_batch_id IS NULL AND reverses_batch_id != id) OR (kind = 'replacement' AND reverses_batch_id IS NULL AND replaces_batch_id IS NOT NULL AND replaces_batch_id != id)), \n\tFOREIGN KEY(audit_event_id) REFERENCES audit_events (id)\n)",
    "CREATE TABLE posting_lines (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\tbatch_id VARCHAR(26) NOT NULL, \n\tline_no BIGINT NOT NULL, \n\taccount_id VARCHAR(26) NOT NULL, \n\tdebit_minor_units BIGINT NOT NULL, \n\tcredit_minor_units BIGINT NOT NULL, \n\tcurrency VARCHAR(3) NOT NULL, \n\taccount_snapshot TEXT NOT NULL, \n\tname_type VARCHAR(16), \n\tname_id VARCHAR(26), \n\tparty_name VARCHAR(200), \n\tclass_id VARCHAR(26), \n\tclass_name VARCHAR(200), \n\tdescription VARCHAR(2000), \n\toriginal_minor_units BIGINT, \n\toriginal_currency VARCHAR(3), \n\trate_used VARCHAR(128), \n\trate_source VARCHAR(64), \n\treversed_line_id VARCHAR(26), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_posting_line_document UNIQUE (transaction_id, id), \n\tCONSTRAINT uq_posting_line_number UNIQUE (batch_id, line_no), \n\tCONSTRAINT uq_posting_line_reversed UNIQUE (reversed_line_id), \n\tCONSTRAINT fk_posting_line_batch FOREIGN KEY(transaction_id, batch_id) REFERENCES posting_batches (transaction_id, id), \n\tCONSTRAINT fk_posting_line_reversed FOREIGN KEY(transaction_id, reversed_line_id) REFERENCES posting_lines (transaction_id, id), \n\tCONSTRAINT ck_ledger_line_no_positive CHECK (typeof(line_no) = 'integer' AND line_no > 0), \n\tCONSTRAINT ck_ledger_account_snapshot_object CHECK (json_valid(account_snapshot) AND json_type(account_snapshot) = 'object'), \n\tCONSTRAINT ck_ledger_party_pair CHECK ((name_type IS NULL AND name_id IS NULL) OR (name_type IN ('customer','vendor','employee','other_name') AND name_id IS NOT NULL)), \n\tCONSTRAINT ck_ledger_foreign_facts CHECK ((original_minor_units IS NULL AND original_currency IS NULL AND rate_used IS NULL AND rate_source IS NULL) OR (typeof(original_minor_units) = 'integer' AND original_minor_units > 0 AND original_currency IS NOT NULL AND rate_used IS NOT NULL AND rate_source IS NOT NULL)), \n\tCONSTRAINT ck_posting_line_one_side CHECK (typeof(debit_minor_units) = 'integer' AND typeof(credit_minor_units) = 'integer' AND ((debit_minor_units > 0 AND credit_minor_units = 0) OR (credit_minor_units > 0 AND debit_minor_units = 0))), \n\tFOREIGN KEY(account_id) REFERENCES accounts (id), \n\tFOREIGN KEY(class_id) REFERENCES classes (id)\n)",
    "CREATE TABLE posting_line_sources (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\tposting_line_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tdocument_line_id VARCHAR(26) NOT NULL, \n\tamount_minor_units BIGINT NOT NULL, \n\tcurrency VARCHAR(3) NOT NULL, \n\treversed_source_id VARCHAR(26), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_posting_source_document UNIQUE (transaction_id, id), \n\tCONSTRAINT uq_posting_source_reversed UNIQUE (reversed_source_id), \n\tCONSTRAINT fk_source_posting_line FOREIGN KEY(transaction_id, posting_line_id) REFERENCES posting_lines (transaction_id, id), \n\tCONSTRAINT fk_source_document_line FOREIGN KEY(transaction_id, revision_id, document_line_id) REFERENCES document_lines (transaction_id, revision_id, id), \n\tCONSTRAINT fk_source_reversed FOREIGN KEY(transaction_id, reversed_source_id) REFERENCES posting_line_sources (transaction_id, id), \n\tCONSTRAINT ck_ledger_amount_minor_units_positive CHECK (typeof(amount_minor_units) = 'integer' AND amount_minor_units > 0)\n)",
    'CREATE INDEX ix_transactions_status_number ON transactions (status, number, id)',
    'CREATE INDEX ix_posting_batches_date ON posting_batches (effective_date, id)',
    'CREATE INDEX ix_posting_batches_document ON posting_batches (transaction_id, id)',
    "CREATE UNIQUE INDEX uq_revision_business_batch ON posting_batches (revision_id) WHERE kind IN ('original', 'replacement')",
    'CREATE INDEX ix_posting_lines_account_batch ON posting_lines (account_id, batch_id)',
    'CREATE INDEX ix_posting_sources_document_line ON posting_line_sources (document_line_id)',
    'CREATE INDEX ix_posting_sources_line ON posting_line_sources (posting_line_id)',
    "CREATE TRIGGER transaction_revisions_no_update BEFORE UPDATE ON transaction_revisions BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER transaction_revisions_no_delete BEFORE DELETE ON transaction_revisions BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER document_line_identities_no_update BEFORE UPDATE ON document_line_identities BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER document_line_identities_no_delete BEFORE DELETE ON document_line_identities BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER document_lines_no_update BEFORE UPDATE ON document_lines BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER document_lines_no_delete BEFORE DELETE ON document_lines BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER posting_batches_no_update BEFORE UPDATE ON posting_batches BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER posting_batches_no_delete BEFORE DELETE ON posting_batches BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER posting_lines_no_update BEFORE UPDATE ON posting_lines BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER posting_lines_no_delete BEFORE DELETE ON posting_lines BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER posting_line_sources_no_update BEFORE UPDATE ON posting_line_sources BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER posting_line_sources_no_delete BEFORE DELETE ON posting_line_sources BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER transactions_no_delete BEFORE DELETE ON transactions BEGIN SELECT RAISE(ABORT, 'business documents are retained'); END",
    "ALTER TABLE sequences ADD COLUMN prefix VARCHAR(16) NOT NULL DEFAULT ''",
    "INSERT INTO sequences (name, next_number, prefix) VALUES ('journal_entry', 1, '')",

)

def upgrade() -> None:
    for statement in DDL:
        op.execute(statement)

def downgrade() -> None:
    raise NotImplementedError("Posted journal history cannot be downgraded")
