"""Frozen service-sales successor DDL; preserves all existing journal facts."""
from alembic import op

revision = 'co0009'
down_revision = 'co0008'
branch_labels = None
depends_on = None

# Literal DDL is independent of application metadata and future schema changes.
DDL = (
    "CREATE TABLE _co0009_transactions (\n\tid VARCHAR(26) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\tupdated_at VARCHAR(32) NOT NULL, \n\tupdated_by VARCHAR(26) NOT NULL, \n\tupdated_via VARCHAR(16) NOT NULL, \n\ttype VARCHAR(32) NOT NULL, \n\tnumber VARCHAR(64) NOT NULL, \n\tcurrent_revision_id VARCHAR(26) NOT NULL, \n\tstatus VARCHAR(16) NOT NULL, \n\tvoided_at VARCHAR(32), \n\tvoided_by VARCHAR(26), \n\tvoid_reason VARCHAR(140), \n\tvoid_posting_batch_id VARCHAR(26), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_transaction_type_number UNIQUE (type, number), \n\tCONSTRAINT ck_transaction_type CHECK (type IN ('journal_entry', 'invoice', 'sales_receipt')), \n\tCONSTRAINT uq_transaction_id_type UNIQUE (id, type), \n\tCONSTRAINT ck_transaction_number CHECK (length(trim(number)) BETWEEN 1 AND 64), \n\tCONSTRAINT ck_transaction_void CHECK ((status = 'posted' AND voided_at IS NULL AND voided_by IS NULL AND void_reason IS NULL AND void_posting_batch_id IS NULL) OR (status = 'voided' AND voided_at IS NOT NULL AND voided_by IS NOT NULL AND length(trim(void_reason)) > 0 AND void_posting_batch_id IS NOT NULL)), \n\tCONSTRAINT fk_transaction_current_revision FOREIGN KEY(id, current_revision_id) REFERENCES transaction_revisions (transaction_id, id) DEFERRABLE INITIALLY DEFERRED, \n\tCONSTRAINT fk_transaction_void_batch FOREIGN KEY(id, void_posting_batch_id) REFERENCES posting_batches (transaction_id, id) DEFERRABLE INITIALLY DEFERRED\n)",
    'INSERT INTO _co0009_transactions (id, version, created_at, created_by, created_via, updated_at, updated_by, updated_via, type, number, current_revision_id, status, voided_at, voided_by, void_reason, void_posting_batch_id) SELECT id, version, created_at, created_by, created_via, updated_at, updated_by, updated_via, type, number, current_revision_id, status, voided_at, voided_by, void_reason, void_posting_batch_id FROM transactions',
    'DROP TABLE transactions',
    'ALTER TABLE _co0009_transactions RENAME TO transactions',
    "CREATE TABLE _co0009_document_lines (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tline_id VARCHAR(26) NOT NULL, \n\tposition BIGINT NOT NULL, \n\tkind VARCHAR(16) NOT NULL, \n\taccount_id VARCHAR(26), \n\tside VARCHAR(6), \n\tamount_minor_units BIGINT, \n\tcurrency VARCHAR(3) NOT NULL, \n\taccount_snapshot TEXT, \n\tname_type VARCHAR(16), \n\tname_id VARCHAR(26), \n\tparty_name VARCHAR(200), \n\tclass_id VARCHAR(26), \n\tclass_name VARCHAR(200), \n\tdescription VARCHAR(2000), \n\toriginal_minor_units BIGINT, \n\toriginal_currency VARCHAR(3), \n\trate_used VARCHAR(128), \n\trate_source VARCHAR(64), \n\tPRIMARY KEY (id), \n\tCONSTRAINT fk_document_line_revision FOREIGN KEY(transaction_id, revision_id) REFERENCES transaction_revisions (transaction_id, id), \n\tCONSTRAINT fk_document_line_identity FOREIGN KEY(transaction_id, line_id) REFERENCES document_line_identities (transaction_id, id), \n\tCONSTRAINT uq_document_line_owner UNIQUE (transaction_id, revision_id, id), \n\tCONSTRAINT uq_document_line_identity UNIQUE (revision_id, line_id), \n\tCONSTRAINT uq_document_line_position UNIQUE (revision_id, position), \n\tCONSTRAINT ck_ledger_position_positive CHECK (typeof(position) = 'integer' AND position > 0), \n\tCONSTRAINT ck_ledger_party_pair CHECK ((name_type IS NULL AND name_id IS NULL) OR (name_type IN ('customer','vendor','employee','other_name') AND name_id IS NOT NULL)), \n\tCONSTRAINT ck_ledger_foreign_facts CHECK ((original_minor_units IS NULL AND original_currency IS NULL AND rate_used IS NULL AND rate_source IS NULL) OR (typeof(original_minor_units) = 'integer' AND original_minor_units > 0 AND original_currency IS NOT NULL AND rate_used IS NOT NULL AND rate_source IS NOT NULL)), \n\tCONSTRAINT ck_document_line_kind_side CHECK ((kind = 'journal' AND account_id IS NOT NULL AND side IS NOT NULL AND side IN ('debit', 'credit') AND typeof(amount_minor_units) = 'integer' AND amount_minor_units > 0 AND account_snapshot IS NOT NULL AND json_valid(account_snapshot) AND json_type(account_snapshot) = 'object') OR (kind = 'sale' AND account_id IS NULL AND side IS NULL AND amount_minor_units IS NULL AND account_snapshot IS NULL AND original_minor_units IS NULL AND original_currency IS NULL AND rate_used IS NULL AND rate_source IS NULL)), \n\tFOREIGN KEY(account_id) REFERENCES accounts (id), \n\tFOREIGN KEY(class_id) REFERENCES classes (id)\n)",
    'INSERT INTO _co0009_document_lines (id, created_at, created_by, created_via, transaction_id, revision_id, line_id, position, kind, account_id, side, amount_minor_units, currency, account_snapshot, name_type, name_id, party_name, class_id, class_name, description, original_minor_units, original_currency, rate_used, rate_source) SELECT id, created_at, created_by, created_via, transaction_id, revision_id, line_id, position, kind, account_id, side, amount_minor_units, currency, account_snapshot, name_type, name_id, party_name, class_id, class_name, description, original_minor_units, original_currency, rate_used, rate_source FROM document_lines',
    'DROP TABLE document_lines',
    'ALTER TABLE _co0009_document_lines RENAME TO document_lines',
    "CREATE TABLE _co0009_posting_line_sources (\n\tid VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\tposting_line_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tdocument_line_id VARCHAR(26) NOT NULL, \n\tamount_minor_units BIGINT NOT NULL, \n\tcurrency VARCHAR(3) NOT NULL, \n\treversed_source_id VARCHAR(26), \n\ttax_component_id VARCHAR(26), \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_posting_source_document UNIQUE (transaction_id, id), \n\tCONSTRAINT uq_posting_source_reversed UNIQUE (reversed_source_id), \n\tCONSTRAINT fk_source_posting_line FOREIGN KEY(transaction_id, posting_line_id) REFERENCES posting_lines (transaction_id, id), \n\tCONSTRAINT fk_source_document_line FOREIGN KEY(transaction_id, revision_id, document_line_id) REFERENCES document_lines (transaction_id, revision_id, id), \n\tCONSTRAINT fk_source_tax_component FOREIGN KEY(transaction_id, revision_id, document_line_id, tax_component_id) REFERENCES sales_tax_components (transaction_id, revision_id, document_line_id, id), \n\tCONSTRAINT fk_source_reversed FOREIGN KEY(transaction_id, reversed_source_id) REFERENCES posting_line_sources (transaction_id, id), \n\tCONSTRAINT ck_ledger_amount_minor_units_positive CHECK (typeof(amount_minor_units) = 'integer' AND amount_minor_units > 0)\n)",
    'INSERT INTO _co0009_posting_line_sources (id, created_at, created_by, created_via, transaction_id, posting_line_id, revision_id, document_line_id, amount_minor_units, currency, reversed_source_id) SELECT id, created_at, created_by, created_via, transaction_id, posting_line_id, revision_id, document_line_id, amount_minor_units, currency, reversed_source_id FROM posting_line_sources',
    'DROP TABLE posting_line_sources',
    'ALTER TABLE _co0009_posting_line_sources RENAME TO posting_line_sources',
    "CREATE TABLE sales_profiles (\n\trevision_id VARCHAR(26) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttype VARCHAR(32) NOT NULL, \n\tcustomer_id VARCHAR(26) NOT NULL, \n\tcontrol_account_id VARCHAR(26) NOT NULL, \n\tdue_date VARCHAR(10), \n\tsubtotal_minor_units BIGINT NOT NULL, \n\ttax_minor_units BIGINT NOT NULL, \n\tprofile_snapshot TEXT NOT NULL, \n\tPRIMARY KEY (revision_id), \n\tCONSTRAINT uq_sales_profile_owner UNIQUE (transaction_id, revision_id), \n\tCONSTRAINT fk_sales_profile_revision FOREIGN KEY(transaction_id, revision_id) REFERENCES transaction_revisions (transaction_id, id), \n\tCONSTRAINT fk_sales_profile_type FOREIGN KEY(transaction_id, type) REFERENCES transactions (id, type), \n\tCONSTRAINT ck_sales_profile_type_due CHECK ((type = 'invoice' AND due_date IS NOT NULL) OR (type = 'sales_receipt' AND due_date IS NULL)), \n\tCONSTRAINT ck_sales_subtotal_minor_units_nonnegative CHECK (typeof(subtotal_minor_units) = 'integer' AND subtotal_minor_units >= 0), \n\tCONSTRAINT ck_sales_tax_minor_units_nonnegative CHECK (typeof(tax_minor_units) = 'integer' AND tax_minor_units >= 0), \n\tCONSTRAINT ck_sales_profile_snapshot_object CHECK (json_valid(profile_snapshot) AND json_type(profile_snapshot) = 'object'), \n\tFOREIGN KEY(customer_id) REFERENCES customers (id), \n\tFOREIGN KEY(control_account_id) REFERENCES accounts (id)\n)",
    "CREATE TABLE sales_line_profiles (\n\tdocument_line_id VARCHAR(26) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\titem_id VARCHAR(26) NOT NULL, \n\tquantity_microunits BIGINT NOT NULL, \n\tunit_id VARCHAR(26), \n\tunit_factor_nanounits BIGINT NOT NULL, \n\tbase_quantity_microunits BIGINT NOT NULL, \n\tunit_price_minor_units BIGINT NOT NULL, \n\tnet_minor_units BIGINT NOT NULL, \n\ttax_minor_units BIGINT NOT NULL, \n\tgross_minor_units BIGINT NOT NULL, \n\titem_snapshot TEXT NOT NULL, \n\tPRIMARY KEY (document_line_id), \n\tCONSTRAINT uq_sales_line_profile_owner UNIQUE (transaction_id, revision_id, document_line_id), \n\tCONSTRAINT fk_sales_line_profile_revision FOREIGN KEY(transaction_id, revision_id) REFERENCES sales_profiles (transaction_id, revision_id), \n\tCONSTRAINT fk_sales_line_profile_line FOREIGN KEY(transaction_id, revision_id, document_line_id) REFERENCES document_lines (transaction_id, revision_id, id), \n\tCONSTRAINT ck_sales_quantity_microunits_positive CHECK (typeof(quantity_microunits) = 'integer' AND quantity_microunits > 0), \n\tCONSTRAINT ck_sales_unit_factor_nanounits_positive CHECK (typeof(unit_factor_nanounits) = 'integer' AND unit_factor_nanounits > 0), \n\tCONSTRAINT ck_sales_base_quantity_microunits_positive CHECK (typeof(base_quantity_microunits) = 'integer' AND base_quantity_microunits > 0), \n\tCONSTRAINT ck_sales_unit_price_minor_units_nonnegative CHECK (typeof(unit_price_minor_units) = 'integer' AND unit_price_minor_units >= 0), \n\tCONSTRAINT ck_sales_net_minor_units_nonnegative CHECK (typeof(net_minor_units) = 'integer' AND net_minor_units >= 0), \n\tCONSTRAINT ck_sales_tax_minor_units_nonnegative CHECK (typeof(tax_minor_units) = 'integer' AND tax_minor_units >= 0), \n\tCONSTRAINT ck_sales_gross_minor_units_nonnegative CHECK (typeof(gross_minor_units) = 'integer' AND gross_minor_units >= 0), \n\tCONSTRAINT ck_sales_item_snapshot_object CHECK (json_valid(item_snapshot) AND json_type(item_snapshot) = 'object'), \n\tFOREIGN KEY(item_id) REFERENCES items (id), \n\tFOREIGN KEY(unit_id) REFERENCES unit_conversions (id)\n)",
    "CREATE TABLE sales_tax_components (\n\tid VARCHAR(26) NOT NULL, \n\ttransaction_id VARCHAR(26) NOT NULL, \n\trevision_id VARCHAR(26) NOT NULL, \n\tdocument_line_id VARCHAR(26) NOT NULL, \n\tcreated_at VARCHAR(32) NOT NULL, \n\tcreated_by VARCHAR(26) NOT NULL, \n\tcreated_via VARCHAR(16) NOT NULL, \n\ttax_item_id VARCHAR(26) NOT NULL, \n\tagency_id VARCHAR(26) NOT NULL, \n\tliability_account_id VARCHAR(26) NOT NULL, \n\trate_percent_millionths BIGINT NOT NULL, \n\ttaxable_minor_units BIGINT NOT NULL, \n\ttax_minor_units BIGINT NOT NULL, \n\tcomponent_snapshot TEXT NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_sales_tax_component_owner UNIQUE (transaction_id, revision_id, document_line_id, id), \n\tCONSTRAINT fk_sales_tax_component_line FOREIGN KEY(transaction_id, revision_id, document_line_id) REFERENCES sales_line_profiles (transaction_id, revision_id, document_line_id), \n\tCONSTRAINT ck_sales_rate_percent_millionths_nonnegative CHECK (typeof(rate_percent_millionths) = 'integer' AND rate_percent_millionths >= 0), \n\tCONSTRAINT ck_sales_taxable_minor_units_nonnegative CHECK (typeof(taxable_minor_units) = 'integer' AND taxable_minor_units >= 0), \n\tCONSTRAINT ck_sales_tax_minor_units_nonnegative CHECK (typeof(tax_minor_units) = 'integer' AND tax_minor_units >= 0), \n\tCONSTRAINT ck_sales_component_snapshot_object CHECK (json_valid(component_snapshot) AND json_type(component_snapshot) = 'object'), \n\tFOREIGN KEY(tax_item_id) REFERENCES items (id), \n\tFOREIGN KEY(agency_id) REFERENCES vendors (id), \n\tFOREIGN KEY(liability_account_id) REFERENCES accounts (id)\n)",
    "CREATE TRIGGER sales_profiles_no_update BEFORE UPDATE ON sales_profiles BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER sales_profiles_no_delete BEFORE DELETE ON sales_profiles BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER sales_line_profiles_no_update BEFORE UPDATE ON sales_line_profiles BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER sales_line_profiles_no_delete BEFORE DELETE ON sales_line_profiles BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER sales_tax_components_no_update BEFORE UPDATE ON sales_tax_components BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "CREATE TRIGGER sales_tax_components_no_delete BEFORE DELETE ON sales_tax_components BEGIN SELECT RAISE(ABORT, 'immutable ledger history'); END",
    "INSERT INTO sequences (name, next_number, prefix) VALUES ('invoice', 1, '')",
    "INSERT INTO sequences (name, next_number, prefix) VALUES ('sales_receipt', 1, '')",
    "CREATE TRIGGER document_lines_type_insert BEFORE INSERT ON document_lines WHEN EXISTS (SELECT 1 FROM transactions WHERE id = NEW.transaction_id AND ((type = 'journal_entry' AND NEW.kind <> 'journal') OR (type IN ('invoice', 'sales_receipt') AND NEW.kind <> 'sale'))) BEGIN SELECT RAISE(ABORT, 'document line kind does not match transaction type'); END",
    "CREATE TRIGGER sales_line_profiles_kind_insert BEFORE INSERT ON sales_line_profiles WHEN EXISTS (SELECT 1 FROM document_lines WHERE id = NEW.document_line_id AND kind <> 'sale') BEGIN SELECT RAISE(ABORT, 'sales profile requires sale line'); END",
)


def upgrade() -> None:
    connection = op.get_bind()
    # Rebuilds drop attached objects. Retain their exact SQL, including any
    # installation-local indexes/triggers, without deriving the successor DDL.
    objects = connection.exec_driver_sql(
        "SELECT sql FROM sqlite_schema WHERE type IN ('index', 'trigger') "
        "AND tbl_name IN ('transactions', 'document_lines', 'posting_line_sources') "
        "AND sql IS NOT NULL ORDER BY type, name"
    ).scalars().all()
    for statement in DDL:
        op.execute(statement)
    for statement in objects:
        connection.exec_driver_sql(statement)
    if connection.exec_driver_sql('PRAGMA foreign_key_check').fetchone() is not None:
        raise RuntimeError('co0009 foreign key check failed')


def downgrade() -> None:
    raise NotImplementedError('Posted sales history cannot be downgraded')
