"""Narrow preserving allocation3 admission; frozen SQL, no live schema metadata."""
import importlib
import re
from alembic import op

revision = 'co0016'
down_revision = 'co0015'
branch_labels = None
depends_on = None
TABLE = 'work_billing_allocations'
TEMPORARY = '_co0016_work_billing_allocations'
REPLACEMENTS = {"CONSTRAINT ck_work_billing_quantity_microunits CHECK ((typeof(quantity_microunits) = 'integer' AND quantity_microunits > 0) OR (allocation_version = 2 AND quantity_microunits IS NULL))": 'CONSTRAINT '
                                                                                                                                                                                             'ck_work_billing_quantity_microunits '
                                                                                                                                                                                             'CHECK '
                                                                                                                                                                                             '((typeof(quantity_microunits) '
                                                                                                                                                                                             '= '
                                                                                                                                                                                             "'integer' "
                                                                                                                                                                                             'AND '
                                                                                                                                                                                             'quantity_microunits '
                                                                                                                                                                                             '> '
                                                                                                                                                                                             '0) '
                                                                                                                                                                                             'OR '
                                                                                                                                                                                             '(allocation_version '
                                                                                                                                                                                             'IN '
                                                                                                                                                                                             '(2,3) '
                                                                                                                                                                                             'AND '
                                                                                                                                                                                             'quantity_microunits '
                                                                                                                                                                                             'IS '
                                                                                                                                                                                             'NULL))',
 "CONSTRAINT ck_work_billing_allocation_version CHECK (typeof(allocation_version) = 'integer' AND allocation_version IN (1,2))": 'CONSTRAINT '
                                                                                                                                 'ck_work_billing_allocation_version '
                                                                                                                                 'CHECK '
                                                                                                                                 '(typeof(allocation_version) '
                                                                                                                                 '= '
                                                                                                                                 "'integer' "
                                                                                                                                 'AND '
                                                                                                                                 'allocation_version '
                                                                                                                                 'IN '
                                                                                                                                 '(1,2,3))',
 "CONSTRAINT ck_work_billing_proof CHECK ((allocation_version = 1 AND source_basis_hash IS NULL AND denominator_hex IS NULL AND spans_json IS NULL) OR (allocation_version = 2 AND typeof(source_basis_hash) = 'text' AND length(source_basis_hash) = 64 AND length(CAST(source_basis_hash AS BLOB)) = 64 AND source_basis_hash NOT GLOB '*[^0-9a-f]*' AND typeof(denominator_hex) = 'text' AND length(denominator_hex) = 40 AND length(CAST(denominator_hex AS BLOB)) = 40 AND denominator_hex NOT GLOB '*[^0-9a-f]*' AND denominator_hex > '0000000000000000000000000000000000000000' COLLATE BINARY AND typeof(spans_json) = 'text' AND CASE WHEN json_valid(spans_json) THEN json_type(spans_json) = 'array' AND json_array_length(spans_json) BETWEEN 1 AND 200 ELSE 0 END))": 'CONSTRAINT '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'ck_work_billing_proof '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'CHECK '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '((allocation_version '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '1 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'source_basis_hash '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'IS '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'NULL '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'denominator_hex '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'IS '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'NULL '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'spans_json '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'IS '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'NULL) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'OR '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '(allocation_version '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'IN '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '(2,3) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'typeof(source_basis_hash) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'text' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'length(source_basis_hash) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '64 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'length(CAST(source_basis_hash '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AS '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'BLOB)) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '64 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'source_basis_hash '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'NOT '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'GLOB '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'*[^0-9a-f]*' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'typeof(denominator_hex) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'text' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'length(denominator_hex) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '40 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'length(CAST(denominator_hex '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AS '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'BLOB)) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '40 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'denominator_hex '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'NOT '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'GLOB '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'*[^0-9a-f]*' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'denominator_hex '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '> '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'0000000000000000000000000000000000000000' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'COLLATE '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'BINARY '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'typeof(spans_json) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'text' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'CASE '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'WHEN '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'json_valid(spans_json) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'THEN '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'json_type(spans_json) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '= '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "'array' "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'json_array_length(spans_json) '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'BETWEEN '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '1 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'AND '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '200 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'ELSE '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    '0 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'END))'}
KNOWN_GUARDS = {'work_billing_allocations_immutable_update': 'CREATE TRIGGER '
                                              'work_billing_allocations_immutable_update BEFORE '
                                              'UPDATE ON work_billing_allocations BEGIN SELECT '
                                              "RAISE(ABORT, 'immutable work billing history'); END",
 'work_billing_allocations_immutable_delete': 'CREATE TRIGGER '
                                              'work_billing_allocations_immutable_delete BEFORE '
                                              'DELETE ON work_billing_allocations BEGIN SELECT '
                                              "RAISE(ABORT, 'immutable work billing history'); END",
 'work_billing_allocation_replace': 'CREATE TRIGGER work_billing_allocation_replace BEFORE INSERT '
                                    'ON work_billing_allocations\n'
                                    'WHEN EXISTS (SELECT 1 FROM work_billing_allocations WHERE id '
                                    '= NEW.id OR\n'
                                    '(revision_id = NEW.revision_id AND root_document_id = '
                                    'NEW.root_document_id AND root_line_id = NEW.root_line_id))\n'
                                    "BEGIN SELECT RAISE(ABORT, 'immutable work billing history'); "
                                    'END',
 'work_billing_allocation_root': 'CREATE TRIGGER work_billing_allocation_root BEFORE INSERT ON '
                                 'work_billing_allocations\n'
                                 'WHEN NOT EXISTS (SELECT 1 FROM work_lines s JOIN '
                                 'work_line_identities i\n'
                                 'ON i.document_id = s.document_id AND i.id = s.line_id\n'
                                 'WHERE s.document_id = NEW.source_document_id AND s.revision_id = '
                                 'NEW.source_revision_id AND s.id = NEW.source_line_id\n'
                                 'AND i.root_document_id = NEW.root_document_id AND i.root_line_id '
                                 '= NEW.root_line_id)\n'
                                 "BEGIN SELECT RAISE(ABORT, 'invalid work billing allocation "
                                 "root'); END",
 'work_billing_allocation_active': 'CREATE TRIGGER work_billing_allocation_active BEFORE INSERT ON '
                                   'work_billing_allocations\n'
                                   'WHEN EXISTS (SELECT 1 FROM work_billing_allocations a JOIN '
                                   'transactions t\n'
                                   'ON t.id = a.transaction_id AND t.current_revision_id = '
                                   "a.revision_id AND t.status = 'posted'\n"
                                   'WHERE a.root_document_id = NEW.root_document_id AND '
                                   'a.root_line_id = NEW.root_line_id\n'
                                   'AND a.transaction_id <> NEW.transaction_id AND '
                                   '(a.allocation_version = 1 OR NEW.allocation_version = 1\n'
                                   ' OR a.source_basis_hash COLLATE BINARY <> '
                                   'NEW.source_basis_hash\n'
                                   ' OR a.denominator_hex COLLATE BINARY <> NEW.denominator_hex\n'
                                   ' OR EXISTS (SELECT 1 FROM json_each(a.spans_json) l\n'
                                   ' CROSS JOIN json_each(CASE WHEN json_valid(NEW.spans_json) '
                                   "THEN NEW.spans_json ELSE '[]' END) r\n"
                                   " WHERE json_extract(l.value, '$[0]') COLLATE BINARY < "
                                   "json_extract(CASE WHEN r.type = 'array' THEN r.value ELSE '[]' "
                                   "END, '$[1]')\n"
                                   " AND json_extract(CASE WHEN r.type = 'array' THEN r.value ELSE "
                                   "'[]' END, '$[0]') COLLATE BINARY < json_extract(l.value, "
                                   "'$[1]'))))\n"
                                   "BEGIN SELECT RAISE(ABORT, 'work billing root already consumed "
                                   "or incompatible basis'); END",
 'work_billing_transaction_insert': 'CREATE TRIGGER work_billing_transaction_insert BEFORE INSERT '
                                    'ON transactions\n'
                                    "WHEN NEW.status = 'posted' AND EXISTS (\n"
                                    'SELECT 1 FROM work_billing_allocations pending JOIN '
                                    'work_billing_allocations active\n'
                                    'ON active.root_document_id = pending.root_document_id AND '
                                    'active.root_line_id = pending.root_line_id\n'
                                    'JOIN transactions t ON t.id = active.transaction_id AND '
                                    't.current_revision_id = active.revision_id AND t.status = '
                                    "'posted'\n"
                                    'WHERE pending.transaction_id = NEW.id AND pending.revision_id '
                                    '= NEW.current_revision_id\n'
                                    'AND active.transaction_id <> NEW.id AND '
                                    '(active.allocation_version = 1 OR pending.allocation_version '
                                    '= 1\n'
                                    ' OR active.source_basis_hash COLLATE BINARY <> '
                                    'pending.source_basis_hash\n'
                                    ' OR active.denominator_hex COLLATE BINARY <> '
                                    'pending.denominator_hex\n'
                                    ' OR EXISTS (SELECT 1 FROM json_each(active.spans_json) l\n'
                                    ' CROSS JOIN json_each(pending.spans_json) r\n'
                                    " WHERE json_extract(l.value, '$[0]') COLLATE BINARY < "
                                    "json_extract(r.value, '$[1]')\n"
                                    " AND json_extract(r.value, '$[0]') COLLATE BINARY < "
                                    "json_extract(l.value, '$[1]'))))\n"
                                    "BEGIN SELECT RAISE(ABORT, 'work billing root already consumed "
                                    "or incompatible basis'); END",
 'work_billing_transaction_update': 'CREATE TRIGGER work_billing_transaction_update BEFORE UPDATE '
                                    'OF current_revision_id, status ON transactions\n'
                                    "WHEN NEW.status = 'posted' AND EXISTS (\n"
                                    'SELECT 1 FROM work_billing_allocations pending JOIN '
                                    'work_billing_allocations active\n'
                                    'ON active.root_document_id = pending.root_document_id AND '
                                    'active.root_line_id = pending.root_line_id\n'
                                    'JOIN transactions t ON t.id = active.transaction_id AND '
                                    't.current_revision_id = active.revision_id AND t.status = '
                                    "'posted'\n"
                                    'WHERE pending.transaction_id = NEW.id AND pending.revision_id '
                                    '= NEW.current_revision_id\n'
                                    'AND active.transaction_id <> NEW.id AND '
                                    '(active.allocation_version = 1 OR pending.allocation_version '
                                    '= 1\n'
                                    ' OR active.source_basis_hash COLLATE BINARY <> '
                                    'pending.source_basis_hash\n'
                                    ' OR active.denominator_hex COLLATE BINARY <> '
                                    'pending.denominator_hex\n'
                                    ' OR EXISTS (SELECT 1 FROM json_each(active.spans_json) l\n'
                                    ' CROSS JOIN json_each(pending.spans_json) r\n'
                                    " WHERE json_extract(l.value, '$[0]') COLLATE BINARY < "
                                    "json_extract(r.value, '$[1]')\n"
                                    " AND json_extract(r.value, '$[0]') COLLATE BINARY < "
                                    "json_extract(l.value, '$[1]'))))\n"
                                    "BEGIN SELECT RAISE(ABORT, 'work billing root already consumed "
                                    "or incompatible basis'); END",
 'work_billing_allocation_shape': 'CREATE TRIGGER work_billing_allocation_shape\n'
                                  'BEFORE INSERT ON work_billing_allocations WHEN '
                                  'NEW.allocation_version = 2\n'
                                  'BEGIN\n'
                                  " SELECT CASE WHEN typeof(NEW.spans_json) <> 'text' OR NOT "
                                  'json_valid(NEW.spans_json)\n'
                                  " THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
                                  " SELECT CASE WHEN json_type(NEW.spans_json) <> 'array'\n"
                                  ' OR json_array_length(NEW.spans_json) NOT BETWEEN 1 AND 200\n'
                                  " THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
                                  ' SELECT CASE WHEN EXISTS (\n'
                                  ' SELECT 1 FROM json_each(NEW.spans_json) s WHERE CASE\n'
                                  " WHEN s.type <> 'array' THEN 1\n"
                                  ' WHEN json_array_length(s.value) <> 2 THEN 1\n'
                                  ' ELSE NOT coalesce(\n'
                                  " json_type(s.value, '$[0]') = 'text' AND json_type(s.value, "
                                  "'$[1]') = 'text'\n"
                                  " AND length(CAST(json_extract(s.value, '$[0]') AS BLOB)) = 40\n"
                                  " AND length(CAST(json_extract(s.value, '$[1]') AS BLOB)) = 40\n"
                                  " AND length(json_extract(s.value, '$[0]')) = 40\n"
                                  " AND length(json_extract(s.value, '$[1]')) = 40\n"
                                  " AND json_extract(s.value, '$[0]') NOT GLOB '*[^0-9a-f]*'\n"
                                  " AND json_extract(s.value, '$[1]') NOT GLOB '*[^0-9a-f]*'\n"
                                  " AND json_extract(s.value, '$[0]') COLLATE BINARY < "
                                  "json_extract(s.value, '$[1]')\n"
                                  " AND json_extract(s.value, '$[1]') COLLATE BINARY <= "
                                  'NEW.denominator_hex, 0)\n'
                                  " END) THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
                                  ' SELECT CASE WHEN EXISTS (\n'
                                  ' SELECT 1 FROM json_each(NEW.spans_json) p JOIN '
                                  'json_each(NEW.spans_json) n ON n.key = p.key + 1\n'
                                  " WHERE json_extract(p.value, '$[1]') COLLATE BINARY >= "
                                  "json_extract(n.value, '$[0]'))\n"
                                  " THEN RAISE(ABORT, 'noncanonical work billing spans') END;\n"
                                  'END'}
OLD_SHAPE = ('CREATE TRIGGER work_billing_allocation_shape\n'
 'BEFORE INSERT ON work_billing_allocations WHEN NEW.allocation_version = 2\n'
 'BEGIN\n'
 " SELECT CASE WHEN typeof(NEW.spans_json) <> 'text' OR NOT json_valid(NEW.spans_json)\n"
 " THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
 " SELECT CASE WHEN json_type(NEW.spans_json) <> 'array'\n"
 ' OR json_array_length(NEW.spans_json) NOT BETWEEN 1 AND 200\n'
 " THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
 ' SELECT CASE WHEN EXISTS (\n'
 ' SELECT 1 FROM json_each(NEW.spans_json) s WHERE CASE\n'
 " WHEN s.type <> 'array' THEN 1\n"
 ' WHEN json_array_length(s.value) <> 2 THEN 1\n'
 ' ELSE NOT coalesce(\n'
 " json_type(s.value, '$[0]') = 'text' AND json_type(s.value, '$[1]') = 'text'\n"
 " AND length(CAST(json_extract(s.value, '$[0]') AS BLOB)) = 40\n"
 " AND length(CAST(json_extract(s.value, '$[1]') AS BLOB)) = 40\n"
 " AND length(json_extract(s.value, '$[0]')) = 40\n"
 " AND length(json_extract(s.value, '$[1]')) = 40\n"
 " AND json_extract(s.value, '$[0]') NOT GLOB '*[^0-9a-f]*'\n"
 " AND json_extract(s.value, '$[1]') NOT GLOB '*[^0-9a-f]*'\n"
 " AND json_extract(s.value, '$[0]') COLLATE BINARY < json_extract(s.value, '$[1]')\n"
 " AND json_extract(s.value, '$[1]') COLLATE BINARY <= NEW.denominator_hex, 0)\n"
 " END) THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
 ' SELECT CASE WHEN EXISTS (\n'
 ' SELECT 1 FROM json_each(NEW.spans_json) p JOIN json_each(NEW.spans_json) n ON n.key = p.key + '
 '1\n'
 " WHERE json_extract(p.value, '$[1]') COLLATE BINARY >= json_extract(n.value, '$[0]'))\n"
 " THEN RAISE(ABORT, 'noncanonical work billing spans') END;\n"
 'END')
NEW_SHAPE = ('CREATE TRIGGER work_billing_allocation_shape\n'
 'BEFORE INSERT ON work_billing_allocations WHEN NEW.allocation_version IN (2,3)\n'
 'BEGIN\n'
 " SELECT CASE WHEN typeof(NEW.spans_json) <> 'text' OR NOT json_valid(NEW.spans_json)\n"
 " THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
 " SELECT CASE WHEN json_type(NEW.spans_json) <> 'array'\n"
 ' OR json_array_length(NEW.spans_json) NOT BETWEEN 1 AND 200\n'
 " THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
 ' SELECT CASE WHEN EXISTS (\n'
 ' SELECT 1 FROM json_each(NEW.spans_json) s WHERE CASE\n'
 " WHEN s.type <> 'array' THEN 1\n"
 ' WHEN json_array_length(s.value) <> 2 THEN 1\n'
 ' ELSE NOT coalesce(\n'
 " json_type(s.value, '$[0]') = 'text' AND json_type(s.value, '$[1]') = 'text'\n"
 " AND length(CAST(json_extract(s.value, '$[0]') AS BLOB)) = 40\n"
 " AND length(CAST(json_extract(s.value, '$[1]') AS BLOB)) = 40\n"
 " AND length(json_extract(s.value, '$[0]')) = 40\n"
 " AND length(json_extract(s.value, '$[1]')) = 40\n"
 " AND json_extract(s.value, '$[0]') NOT GLOB '*[^0-9a-f]*'\n"
 " AND json_extract(s.value, '$[1]') NOT GLOB '*[^0-9a-f]*'\n"
 " AND json_extract(s.value, '$[0]') COLLATE BINARY < json_extract(s.value, '$[1]')\n"
 " AND json_extract(s.value, '$[1]') COLLATE BINARY <= NEW.denominator_hex, 0)\n"
 " END) THEN RAISE(ABORT, 'invalid work billing spans') END;\n"
 ' SELECT CASE WHEN EXISTS (\n'
 ' SELECT 1 FROM json_each(NEW.spans_json) p JOIN json_each(NEW.spans_json) n ON n.key = p.key + '
 '1\n'
 " WHERE json_extract(p.value, '$[1]') COLLATE BINARY >= json_extract(n.value, '$[0]'))\n"
 " THEN RAISE(ABORT, 'noncanonical work billing spans') END;\n"
 'END')


def _plan(connection):
    preserving = importlib.import_module('bookflow.storage.company_migrations.versions.0012_progress_billing')
    quote = preserving._quote
    sql = connection.exec_driver_sql("SELECT sql FROM sqlite_schema WHERE type='table' AND name=?", (TABLE,)).scalar_one()
    _, parts, suffix = preserving._definitions(sql, TABLE)
    columns = connection.exec_driver_sql(f'PRAGMA table_xinfo({quote(TABLE)})').all()
    if any(row[1].lower() in ('rowid', '_rowid_', 'oid') for row in columns) or 'WITHOUT' in suffix.upper():
        raise RuntimeError('co0016 cannot preserve custom row identity')
    for old, new in REPLACEMENTS.items():
        found = [i for i, part in enumerate(parts) if part.strip() == old]
        if len(found) != 1:
            raise RuntimeError('co0016 unrecognized owned constraint: ' + old)
        parts[found[0]] = parts[found[0]].replace(old, new, 1)
    create = 'CREATE TABLE ' + quote(TEMPORARY) + ' (' + ','.join(parts) + suffix
    writable = ','.join(['rowid'] + [quote(row[1]) for row in columns if row[6] == 0])
    selected = ','.join(['rowid'] + [expr for row in columns for expr in
        (f'typeof({quote(row[1])})', f'quote({quote(row[1])})', f'CAST({quote(row[1])} AS BLOB)')])
    return create, writable, selected


def _accept(connection):
    if connection.exec_driver_sql('PRAGMA integrity_check').all() != [('ok',)]:
        raise RuntimeError('co0016 integrity check failed')
    if connection.exec_driver_sql('PRAGMA foreign_key_check').fetchone() is not None:
        raise RuntimeError('co0016 foreign key check failed')


def upgrade():
    connection = op.get_bind()
    preserving = importlib.import_module('bookflow.storage.company_migrations.versions.0012_progress_billing')
    quote = preserving._quote
    if connection.exec_driver_sql('SELECT 1 FROM sqlite_schema WHERE lower(name)=lower(?)', (TEMPORARY,)).first():
        raise RuntimeError('co0016 reserved temporary name already exists')
    create, writable, selected = _plan(connection)
    retained = connection.exec_driver_sql("SELECT type,name,sql FROM sqlite_schema WHERE sql IS NOT NULL AND (type IN ('view','trigger') OR (type='index' AND tbl_name='work_billing_allocations')) ORDER BY CASE type WHEN 'view' THEN 0 WHEN 'index' THEN 1 ELSE 2 END,name").all()
    stored = {name: sql for kind,name,sql in retained if kind == 'trigger'}
    if any(stored.get(name) != sql for name,sql in KNOWN_GUARDS.items()):
        raise RuntimeError('co0016 unrecognized owned allocation guard')
    for name,sql in stored.items():
        if name not in KNOWN_GUARDS and re.search(r'(?i)\ballocation_version\b',sql) and re.search(r'(?i)\bON\s+["`\[]?work_billing_allocations\b',sql):
            raise RuntimeError('co0016 unknown competing allocation discriminator guard')
    for kind in ('trigger','view'):
        for object_kind,name,_ in retained:
            if object_kind == kind:
                connection.exec_driver_sql(f'DROP {kind.upper()} main.{quote(name)}')
    connection.exec_driver_sql(create)
    connection.exec_driver_sql(f'INSERT INTO {quote(TEMPORARY)} ({writable}) SELECT {writable} FROM {quote(TABLE)}')
    for left,right in ((TABLE,TEMPORARY),(TEMPORARY,TABLE)):
        if connection.exec_driver_sql(f'SELECT {selected} FROM {quote(left)} EXCEPT SELECT {selected} FROM {quote(right)}').first():
            raise RuntimeError('co0016 rebuilt raw values differ')
    connection.exec_driver_sql(f'DROP TABLE {quote(TABLE)}')
    connection.exec_driver_sql(f'ALTER TABLE {quote(TEMPORARY)} RENAME TO {quote(TABLE)}')
    for kind,name,sql in retained:
        connection.exec_driver_sql(NEW_SHAPE if name == 'work_billing_allocation_shape' and kind == 'trigger' else sql)
    _accept(connection)


def downgrade():
    raise NotImplementedError
